INSERT INTO `store_categories` (`display_name`, `description`, `require_plugin`, `web_color`) VALUES 
	('Trails', 'Magical trails that follow your character.', 'trails', 'FFD700');
	
set @category_id = (select last_insert_id());

INSERT INTO `store_items` (`name`, `display_name`, `description`, `type`, `loadout_slot`, `price`, `category_id`, `attrs`) VALUES
('cocacola', 'Coca Cola', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/cocacola.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('leaves1', 'Leaves', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/leaves1.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('_fire', 'Fire', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/fire1.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('ice', 'Ice', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/ice.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('metal', 'Metal', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/metallic1.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('peace', 'Peace', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/peace.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('earth', 'Earth', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/earth.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('wheel', 'Wheel', NULL, 'trails', 'trails', 250, @category_id, '{ "material": "materials/sprites/trails/wheel.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('awesome', 'Awesome', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/awesome.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('star', 'Star', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/star.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('mushroom', 'Mushroom', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/mushroom.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('crackedbeam', 'Cracked Beam', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/crackedbeam.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('arrows', 'Arrows', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/arrows.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('wings', 'Wings', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/wings.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('crown', 'Crown', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/crown.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('dna', 'DNA', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/dna2.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('paintsplatter', 'Paint Splatter', NULL, 'trails', 'trails', 400, @category_id, '{ "material": "materials/sprites/trails/paintsplatter.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('doublerainbow', 'Double Rainbow', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/doublerainbow.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('banknote', 'Bank Note', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/banknote.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('biohazard', 'Biohazard', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/biohazard.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('bombomb', 'Bombomb', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/bombomb.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('boo', 'Boo', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/boo.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('hellokitty', 'Hello Kitty', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/hellokitty.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('hypnotic', 'Hypnotic', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/hypnotic.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('mario', 'Mario', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/mario.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('medic', 'Medic', NULL, 'trails', 'trails', 800, @category_id, '{ "material": "materials/sprites/trails/medic.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('pinkribbon', 'Pink Ribbon', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/pinkribbon.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('poker', 'Poker', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/poker.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('potleaf', 'Pot Leaf', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/potleaf.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('pretzel', 'Pretzel', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/pretzel.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('psychball', 'Psych ball', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/psychball.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('seprainbow', 'Seprainbow', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/seprainbow.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('skullnbones', 'Skulln Bones', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/skullnbones.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('swirly', 'Swirly', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/swirly.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('taco', 'Taco', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/taco.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('trippy', 'Trippy', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/trippy.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('usflag', 'Us Flag', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/usflag.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('warrior', 'Warrior', NULL, 'trails', 'trails', 1000, @category_id, '{ "material": "materials/sprites/trails/warrior.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('arrowrainbow', 'Arrow Rainbow', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/arrowrainbow.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('beermug', 'Beer Mug', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/beermug.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('blade', 'Blade', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/blade.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('bulletbill', 'Bullet Bill', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/bulletbill.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('bluelightning', 'Blue Lightning', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/bluelightning.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('candies', 'Candies', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/candies.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('colorbolt', 'Color Bolt', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/colorbolt.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('cookies', 'Cookies', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/cookies.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('donuts', 'Donuts', NULL, 'trails', 'trails', 1200, @category_id, '{ "material": "materials/sprites/trails/donuts.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('energy', 'Energy', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/energy.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('energyball', 'Energy Ball', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/energyball.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('footprint', 'Foot Print', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/footprint.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('germanflag', 'German Flag', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/germanflag.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('goomba', 'Goomba', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/goomba.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('grenade', 'Grenade', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/grenade.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('gummybears', 'Gummy Bears', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/gummybears.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('handgun', 'Hand Gun', NULL, 'trails', 'trails', 2000, @category_id, '{ "material": "materials/sprites/trails/handgun.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('lightspeed', 'Light Speed', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/lightspeed.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('lol', 'Lol', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/lol.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('pacman', 'Pacman', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/pacman.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('pawprint', 'Paw Print', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/pawprint.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('skull', 'Skull', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/skull.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('ukflag', 'UK Flag', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/ukflag.vmt", "color": "255 255 255", "startingwidth": 10 }'),
('words', 'Words', NULL, 'trails', 'trails', 2400, @category_id, '{ "material": "materials/sprites/trails/words.vmt", "color": "255 255 255", "startingwidth": 10 }');