INSERT INTO `store_categories` (`display_name`, `description`, `require_plugin`, `web_color`) VALUES 
	('Trails', 'Magical trails that follow your character.', 'trails', 'FFD700');
	
set @category_id = (select last_insert_id());

INSERT INTO `store_items` (`name`, `display_name`, `description`, `type`, `loadout_slot`, `price`, `category_id`, `attrs`) VALUES
('trail_8bitmushroom', '8-bit Mushroom', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/8bitmushroom.vmt" }'),
('trail_8bitpow', '8-bit Pow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/8bitpow.vmt" }'),
('trail_abstract', 'Abstract', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/abstract.vmt" }'),
('trail_airforce', 'Airforce', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/airforce.vmt" }'),
('trail_airforce2', 'Airforce 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/airforce2.vmt" }'),
('trail_apple', 'Apple', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/apple.vmt" }'),
('trail_arrowrainbow', 'Arrow Rainbow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/arrowrainbow.vmt" }'),
('trail_arrows', 'Arrows', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/arrows.vmt" }'),
('trail_assasin', 'Assasin', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/assasin.vmt" }'),
('trail_awesome', 'Awesome', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/awesome.vmt" }'),
('trail_awesomeface', 'Awesome Face', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/awesomeface.vmt" }'),
('trail_awesome_sad', 'Awesome Sad', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/awesome_sad.vmt" }'),
('trail_babyand', 'Babyand', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/babyand.vmt" }'),
('trail_banknote', 'Banknote', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/banknote.vmt" }'),
('trail_barcelona', 'Barcelona', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/barcalona.vmt" }'),
('trail_batman', 'Batman', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/batman.vmt" }'),
('trail_battlefield', 'Battlefield', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/battlefield.vmt" }'),
('trail_beermug', 'Beermug', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/beermug.vmt" }'),
('trail_biohazard', 'Biohazard', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/biohazard.vmt" }'),
('trail_blade', 'Blade', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/blade.vmt" }'),
('trail_bluelightning', 'Blue Lightning', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/bluelightning.vmt" }'),
('trail_bmwlogo', 'BMW logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/bmwlogo.vmt" }'),
('trail_bombomb', 'Bombomb', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/bombomb.vmt" }'),
('trail_boo', 'Boo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/boo.vmt" }'),
('trail_bulletbill', 'Bulletbill', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/bulletbill.vmt" }'),
('trail_bullets', 'Bullets', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/bullets.vmt" }'),
('trail_canadaflag', 'Canada Flag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/canadaflag.vmt" }'),
('trail_candies', 'Candies', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/candies.vmt" }'),
('trail_ccole', 'Ccole', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ccole.vmt" }'),
('trail_cereal-guy', 'Cereal Guy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/cereal-guy.vmt" }'),
('trail_challenge', 'Challenge', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/challenge.vmt" }'),
('trail_chopped_pyro', 'Chopped Pyro', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/chopped_pyro.vmt" }'),
('trail_chrislight', 'Chrislight', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/chrislight.vmt" }'),
('trail_christlights', 'Christ Lights', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/christlights.vmt" }'),
('trail_cocacola', 'Coca Cola', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/cocacola.vmt" }'),
('trail_cocacola2', 'Coca Cola 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/cocacola2.vmt" }'),
('trail_colorbolt', 'Colorbolt', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/colorbolt.vmt" }'),
('trail_cookies', 'Cookies', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/cookies.vmt" }'),
('trail_crackedbeam', 'Cracked Beam', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/crackedbeam.vmt" }'),
('trail_creed', 'Creed', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/creed.vmt" }'),
('trail_creeper', 'Creeper', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/creeper.vmt" }'),
('trail_crown', 'Crown', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/crown.vmt" }'),
('trail_damnimgood', 'Damn Im Good', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/damnimgood.vmt" }'),
('trail_danishflag', 'Danish Flag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/danishflag.vmt" }'),
('trail_darkknight', 'Dark Knight', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/darkknight.vmt" }'),
('trail_deadmau5', 'Deadmau5', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/deadmau5.vmt" }'),
('trail_deadmau52', 'Deadmau5 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/deadmau52.vmt" }'),
('trail_deadmau53', 'Deadmau5 3', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/deadmau53.vmt" }'),
('trail_deadmau54', 'Deadmau5 4', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/deadmau54.vmt" }'),
('trail_deadpool', 'Deadpool', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/deadpool.vmt" }'),
('trail_devil_smiley', 'Devil Smiley', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/devil_smiley.vmt" }'),
('trail_dirt', 'Dirt', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/dirt.vmt" }'),
('trail_disorderdragonv2', 'Disorder Dragon', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/disorderdragonv2.vmt" }'),
('trail_disorderlogo2', 'Disorder Logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/disorderlogo2.vmt" }'),
('trail_disordertext10', 'Disorder Text', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/disordertext10.vmt" }'),
('trail_dna2', 'DNA', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/dna2.vmt" }'),
('trail_dollars', 'Dollars', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/dollars.vmt" }'),
('trail_donuts', 'Donuts', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/donuts.vmt" }'),
('trail_doublerainbow', 'Double Rainbow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/doublerainbow.vmt" }'),
('trail_dragon', 'Dragon', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/dragon.vmt" }'),
('trail_dragondisorder', 'Dragon Disorder', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/dragondisorder.vmt" }'),
('trail_eafifa', 'EA FIFA', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/eafifa.vmt" }'),
('trail_ealogo', 'Ealogo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ealogo.vmt" }'),
('trail_earth', 'Earth', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/earth.vmt" }'),
('trail_energy', 'Energy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/energy.vmt" }'),
('trail_energyball', 'Energyball', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/energyball.vmt" }'),
('trail_epicsax', 'Epic Sax', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/epicsax.vmt" }'),
('trail_facebookicon', 'Facebook', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/facebookicon.vmt" }'),
('trail_fapface', 'Fap Face', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fapface.vmt" }'),
('trail_faxekondi', 'Faxe Kondi', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/faxekondi.vmt" }'),
('trail_ferrari', 'Ferrari', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ferrari.vmt" }'),
('trail_fire', 'Fire', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fire.vmt" }'),
('trail_fire1', 'Fire 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fire1.vmt" }'),
('trail_firefox', 'FireFox', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/firefox.vmt" }'),
('trail_fireman', 'Fire Man', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fireman.vmt" }'),
('trail_fire_line', 'Fire Line', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fire_line.vmt" }'),
('trail_footprint', 'Footprint', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/footprint.vmt" }'),
('trail_foreveralone', 'Forever Alone', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/foreveralone.vmt" }'),
('trail_fuu1', 'Fuu 1', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fuu1.vmt" }'),
('trail_fuu2', 'Fuu 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fuu2.vmt" }'),
('trail_fyeah', 'Fyeah', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/fyeah.vmt" }'),
('trail_germanflag', 'German Flag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/germanflag.vmt" }'),
('trail_golden_mushroom', 'Golden Mushroom', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/golden_mushroom.vmt" }'),
('trail_googlechrome', 'Google Chrome', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/googlechrome.vmt" }'),
('trail_goomba', 'Goomba', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/goomba.vmt" }'),
('trail_grenade', 'Grenade', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/grenade.vmt" }'),
('trail_gummybears', 'Gummybears', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/gummybears.vmt" }'),
('trail_gusta', 'Gusta', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/gusta.vmt" }'),
('trail_halflife', 'Half-Life', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/halflife.vmt" }'),
('trail_handgun', 'Handgun', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/handgun.vmt" }'),
('trail_headshot', 'Headshot', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/headshot.vmt" }'),
('trail_heart', 'Heart', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/heart.vmt" }'),
('trail_hellokitty', 'Hello Kitty', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/hellokitty.vmt" }'),
('trail_hex', 'Hex', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/hex.vmt" }'),
('trail_hypnotic', 'Hypnotic', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/hypnotic.vmt" }'),
('trail_hypnotoad', 'Hypnotoad', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/hypnotoad.vmt" }'),
('trail_ice', 'Ice', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ice.vmt" }'),
('trail_ice1', 'Ice 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ice1.vmt" }'),
('trail_icloud', 'iCloud', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/icloud.vmt" }'),
('trail_invisible_bike', 'Invisible Bike', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/invisible_bike.vmt" }'),
('trail_jackass', 'Jackass', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/jackass.vmt" }'),
('trail_jester', 'Jester', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/jester.vmt" }'),
('trail_kaleidoscope', 'Kaleidoscope', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/kaleidoscope.vmt" }'),
('trail_kingdomhearts', 'Kingdom Hearts', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/kingdomhearts.vmt" }'),
('trail_kirby', 'Kirby', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/kirby.vmt" }'),
('trail_latvia', 'Latvia', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/latvia.vmt" }'),
('trail_leaves', 'Leaves', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/leaves.vmt" }'),
('trail_leaves1', 'Leaves 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/leaves1.vmt" }'),
('trail_leaves2', 'Leaves 3', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/leaves2.vmt" }'),
('trail_leaves21', 'Leaves 4', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/leaves21.vmt" }'),
('trail_lightning2', 'Lightning', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lightning2.vmt" }'),
('trail_lightning3', 'Lightning 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lightning3.vmt" }'),
('trail_lightspeed', 'Lightspeed', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lightspeed.vmt" }'),
('trail_lightwave', 'Lightwave', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lightwave.vmt" }'),
('trail_lol', 'LOL', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lol.vmt" }'),
('trail_lolguy', 'LOL Guy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/lolguy.vmt" }'),
('trail_mario', 'Mario', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mario.vmt" }'),
('trail_masterchief', 'Masterchief', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/masterchief.vmt" }'),
('trail_mcdonald', 'McDonald', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mcdonald.vmt" }'),
('trail_medic', 'Medic', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/medic.vmt" }'),
('trail_metallic', 'Metallic', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/metallic.vmt" }'),
('trail_metallic1', 'Metallic 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/metallic1.vmt" }'),
('trail_metalskull', 'Metal Skull', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/metalskull.vmt" }'),
('trail_metroid', 'Metroid', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/metroid.vmt" }'),
('trail_mickymouse', 'Micky Mouse', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mickymouse.vmt" }'),
('trail_minecraft', 'Minecraft', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/minecraft.vmt" }'),
('trail_moneybag', 'Moneybag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/moneybag.vmt" }'),
('trail_mtvlogo', 'MTV logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mtvlogo.vmt" }'),
('trail_mudkip', 'Mudkip', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mudkip.vmt" }'),
('trail_multipexles', 'Multipexles', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/multipexles.vmt" }'),
('trail_mushroom', 'Mushroom', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mushroom.vmt" }'),
('trail_mushroom2', 'Mushroom 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/mushroom2.vmt" }'),
('trail_nevergup', 'Nevergup', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/nevergup.vmt" }'),
('trail_nyan', 'Nyan', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/nyan.vmt" }'),
('trail_ocarina', 'Ocarina', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ocarina.vmt" }'),
('trail_okami', 'Okami', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/okami.vmt" }'),
('trail_okayguy', 'Okay Guy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/okayguy.vmt" }'),
('trail_one_piece', 'One Piece', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/one_piece.vmt" }'),
('trail_oops', 'Oops', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/oops.vmt" }'),
('trail_orly', 'Orly', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/orly.vmt" }'),
('trail_pacman', 'PacMan', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pacman.vmt" }'),
('trail_paintsplatter', 'Paint Splatter', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/paintsplatter.vmt" }'),
('trail_panda', 'Panda', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/panda.vmt" }'),
('trail_pawprint', 'Paw Print', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pawprint.vmt" }'),
('trail_peace', 'Peace', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/peace.vmt" }'),
('trail_pedobear', 'Pedobear', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pedobear.vmt" }'),
('trail_pfffft', 'Pfffft', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pfffft.vmt" }'),
('trail_pika', 'Pika', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pika.vmt" }'),
('trail_pikmin', 'Pikmin', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pikmin.vmt" }'),
('trail_pinkie', 'Pinkie', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pinkie.vmt" }'),
('trail_pinkribbon', 'Pink Ribbon', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pinkribbon.vmt" }'),
('trail_playboy', 'Playboy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/playboy.vmt" }'),
('trail_plur', 'Plur', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/plur.vmt" }'),
('trail_pokeball', 'Pokeball', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pokeball.vmt" }'),
('trail_pokemon', 'Pokemon', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pokemon.vmt" }'),
('trail_poker', 'Poker', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/poker.vmt" }'),
('trail_police', 'Police', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/police.vmt" }'),
('trail_potleaf', 'Potleaf', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/potleaf.vmt" }'),
('trail_pretzel', 'Pretzel', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pretzel.vmt" }'),
('trail_problems_face', 'Problems Face', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/problems_face.vmt" }'),
('trail_psychball', 'Psychball', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/psychball.vmt" }'),
('trail_psychtriangle', 'Psychtriangle', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/psychtriangle.vmt" }'),
('trail_pumpkin', 'Pumpkin', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pumpkin.vmt" }'),
('trail_purplelightning', 'Purple Lightning', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/purplelightning.vmt" }'),
('trail_puttegris', 'Puttegris', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/puttegris.vmt" }'),
('trail_pwned', 'Pwned', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/pwned.vmt" }'),
('trail_quake', 'Quake', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/quake.vmt" }'),
('trail_question', 'Question', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/question.vmt" }'),
('trail_raf', 'Raf', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/raf.vmt" }'),
('trail_rain', 'Rain', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/rain.vmt" }'),
('trail_rainbow-dash', 'Rainbow Dash', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/rainbow-dash.vmt" }'),
('trail_rainbow', 'Rainbow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/rainbow.vmt" }'),
('trail_rainbowcobra2', 'Rainbow Cobra', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/rainbowcobra2.vmt" }'),
('trail_rainbowcry', 'Rainbow Cry', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/rainbowcry.vmt" }'),
('trail_realmadrid', 'Real Madrid', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/realmadrid.vmt" }'),
('trail_reaper', 'Reaper', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/reaper.vmt" }'),
('trail_retroegg', 'Retro Egg', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/retroegg.vmt" }'),
('trail_retroflower', 'Retro Flower', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/retroflower.vmt" }'),
('trail_seprainbow', 'Seprainbow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/seprainbow.vmt" }'),
('trail_sharingan', 'Sharingan', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/sharingan.vmt" }'),
('trail_shell', 'Shell', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/shell.vmt" }'),
('trail_shroom5', 'Shroom', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/shroom5.vmt" }'),
('trail_skull', 'Skull', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/skull.vmt" }'),
('trail_skullnbones', 'Skull and bones', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/skullnbones.vmt" }'),
('trail_skypelogo', 'Skype Logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/skypelogo.vmt" }'),
('trail_slowpoke', 'Slow Poke', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/slowpoke.vmt" }'),
('trail_smiley', 'Smiley', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/smiley.vmt" }'),
('trail_smirnoff', 'Smirnoff', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/smirnoff.vmt" }'),
('trail_smugleaf', 'Smug Leaf', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/smugleaf.vmt" }'),
('trail_snowman', 'Snowman', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/snowman.vmt" }'),
('trail_sonylogo', 'Sony Logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/sonylogo.vmt" }'),
('trail_sos', 'SOS', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/sos.vmt" }'),
('trail_spider', 'Spider', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/spider.vmt" }'),
('trail_spongebob', 'Spongebob', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/spongebob.vmt" }'),
('trail_spotify', 'Spotify', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/spotify.vmt" }'),
('trail_srsface', 'SRS face', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/srsface.vmt" }'),
('trail_star', 'Star', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/star.vmt" }'),
('trail_supermanlogo', 'Superman Logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/supermanlogo.vmt" }'),
('trail_swirl', 'Swirl', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/swirl.vmt" }'),
('trail_swirly', 'Swirly', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/swirly.vmt" }'),
('trail_taco', 'Taco', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/taco.vmt" }'),
('trail_test1000', 'Test1000', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/test1000.vmt" }'),
('trail_timebomb', 'Timebomb', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/timebomb.vmt" }'),
('trail_tmishit', 'Tmishit', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/tmishit.vmt" }'),
('trail_triforce', 'Triforce', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/triforce.vmt" }'),
('trail_trippy', 'Trippy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/trippy.vmt" }'),
('trail_trollface', 'Trollface', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/trollface.vmt" }'),
('trail_tux', 'Tux', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/tux.vmt" }'),
('trail_twitter', 'Twitter', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/twitter.vmt" }'),
('trail_ukflag', 'UK Flag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ukflag.vmt" }'),
('trail_ultra', 'Ultra', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/ultra.vmt" }'),
('trail_umbrellacorp', 'Umbrella Corp', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/umbrellacorp.vmt" }'),
('trail_uparrow', 'Up Arrow', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/uparrow.vmt" }'),
('trail_usflag', 'US lag', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/usflag.vmt" }'),
('trail_warheads', 'Warheads', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/warheads.vmt" }'),
('trail_warrior', 'Warrior', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/warrior.vmt" }'),
('trail_water2', 'Water', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/water2.vmt" }'),
('trail_water_elemantary', 'Water Elemantary', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/water_elemantary.vmt" }'),
('trail_wheel', 'Wheel', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/wheel.vmt" }'),
('trail_windows', 'Windows', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/windows.vmt" }'),
('trail_wings', 'Wings', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/wings.vmt" }'),
('trail_wolf', 'Wolf', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/wolf.vmt" }'),
('trail_wonder_woman', 'Wonder Woman', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/wonder_woman.vmt" }'),
('trail_words', 'Words', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/words.vmt" }'),
('trail_xboxlogo', 'Xbox Logo', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/xboxlogo.vmt" }'),
('trail_x_medic', 'X Medic', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/x_medic.vmt" }'),
('trail_y-u-no-guy', 'Y-u-no-guy', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/y-u-no-guy.vmt" }'),
('trail_yingyang', 'Yingyang', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/yingyang.vmt" }'),
('trail_yingyang2', 'Yingyang 2', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/yingyang2.vmt" }'),
('trail_yukari', 'Yukari', NULL, 'trails', 'trails', 300, @category_id, '{ "material": "materials/sprites/store/trails/yukari.vmt" }');